WalmartWeb/Areas/Admin/Controllers/CategoryController.cs
using Walmart.DataAccess.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using Walmart.Model.Models;
using Walmart.Utility;

namespace WalmartWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class CategoryController : Controller
    {
        private readonly IUnitOfWork _db;

        public CategoryController(IUnitOfWork db)
        {
            _db = db;
        }


        public IActionResult Index()
        {
            IEnumerable<Category> categories = _db.Category.GetAll();
            return View(categories.OrderBy(x => x.DisplayOrder));
        }

        public IActionResult Upsert(int? Id)
        {
            if (Id == 0 || Id == null)
            {
                Category category = new Category();
                return View(category);
            }
            else
            {
                Category category = _db.Category.Get(u => u.Id == Id);
                return View(category);
            }
        }

        [HttpPost]
        public IActionResult Upsert(Category category)
        {
            if (ModelState.IsValid)
            {
                if (category.Id != 0)
                {
                    _db.Category.Update(category);
                    _db.Commit();
                    TempData["success"] = "Category Updated Successful!!";
                    return RedirectToAction("Index");
                }
                else
                {
                    _db.Category.Add(category);
                    _db.Commit();
                    TempData["success"] = "Category Added Successful!!";
                    return RedirectToAction("Index");
                }
            }
            return View();
        }

        public IActionResult Edit(int? Id)
        {
            if (Id != 0 || Id != null)
            {
                Category category = _db.Category.Get(u => u.Id == Id);
                if (category != null)
                {
                    return View(category);
                }
            }
            return View();
        }

        [HttpPost]
        public IActionResult Edit(Category category)
        {
            if (ModelState.IsValid)
            {
                _db.Category.Update(category);
                _db.Commit();
            }
            return View();
        }

        #region APICall
        [HttpGet]
        public IActionResult GetAll()
        {
            IEnumerable<Category> categories = _db.Category.GetAll();
            return Json(new { data = categories.OrderBy(u => u.DisplayOrder) });
        }


        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            Category categoryToBeDeleted = _db.Category.Get(u => u.Id == id);
            if (categoryToBeDeleted == null)
            {
                return Json(new { success = false, message = "Error while deleteing" });
            }
            _db.Category.Remove(categoryToBeDeleted);
            _db.Commit();
            return Json(new { success = true, message = "Delete Successful!!" });

        }

        #endregion

    }
}

WalmartWeb/Areas/Admin/Controllers/CompanyController.cs
using Walmart.DataAccess.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Walmart.Model.Models;
using Walmart.Utility;

namespace WalmartWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class CompanyController : Controller
    {
        private readonly IUnitOfWork _db;

        public CompanyController(IUnitOfWork db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<Company> companies= _db.Company.GetAll().ToList();

            return View(companies);
        }
        public IActionResult Upsert(int? Id)
        {
            if (Id == 0 || Id == null)
            {
                Company company = new Company();
                return View(company);
            }
            else
            {
                Company company = _db.Company.Get(u => u.Id == Id);
                return View(company);
            }
        }

        [HttpPost]
        public IActionResult Upsert(Company company)
        {
            if (ModelState.IsValid)
            {
                if (company.Id != 0)
                {
                    _db.Company.Update(company);
                    _db.Commit();
                    TempData["success"] = "Company Updated Successful!!";
                    return RedirectToAction("Index");
                }
                else
                {
                    _db.Company.Add(company);
                    _db.Commit();
                    TempData["success"] = "Company Added Successful!!";
                    return RedirectToAction("Index");
                }
            }
            return View();
        }

        public IActionResult Edit(int? Id)
        {
            if (Id != 0 || Id != null)
            {
                Company company = _db.Company.Get(u => u.Id == Id);
                if (company != null)
                {
                    return View(company);
                }
            }
            return View();
        }

        [HttpPost]
        public IActionResult Edit(Company company)
        {
            if (ModelState.IsValid)
            {
                _db.Company.Update(company);
                _db.Commit();
            }
            return View();
        }

        #region APICall
        [HttpGet]
        public IActionResult GetAll()
        {
            IEnumerable<Company> companies = _db.Company.GetAll();
            return Json(new { data = companies });
        }


        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            Company companyToBeDeleted = _db.Company.Get(u => u.Id == id);
            if (companyToBeDeleted == null)
            {
                return Json(new { success = false, message = "Error while deleteing" });
            }
            _db.Company.Remove(companyToBeDeleted);
            _db.Commit();
            return Json(new { success = true, message = "Delete Successful!!" });

        }

        #endregion

    }
}

WalmartWeb/Areas/Admin/Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Razorpay.Api;
using Stripe.V2;
using System.Diagnostics;
using System.Security.Claims;
using System.Security.Cryptography;
using System.Text;
using Walmart.DataAccess.Repository.IRepository;
using Walmart.Model.Models;
using Walmart.Utility;
using WalmartWeb.Areas.Customer.Controllers;

namespace WalmartWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class OrderController : Controller
    {
        private readonly IUnitOfWork _db;
        private readonly RazorpayService _razorpayService;


        [BindProperty]
        public OrderVM OrderVM { get; set; }

        public OrderController(IUnitOfWork db, RazorpayService razorpayService)
        {
            _db = db;
            _razorpayService = razorpayService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Details(int orderId)
        {
            OrderVM= new()
            {
                OrderHeader = _db.OrderHeader.Get(u => u.Id == orderId, includeProperties: "ApplicationUser"),
                OrderDetail = _db.OrderDetail.GetAll(u => u.OrderHeaderId == orderId, includeProperties: "Product")
            };

            return View(OrderVM);
        }

        [ActionName("Details")]
        [HttpPost]
        public IActionResult Details_PayNow(int orderId)
        {

            OrderVM.OrderHeader = _db.OrderHeader.Get(u => u.Id == orderId, includeProperties: "ApplicationUser");
            OrderVM.OrderDetail = _db.OrderDetail.GetAll(u => u.OrderHeaderId == orderId, includeProperties: "Product");

            var razorOrderId = CreateOrder(OrderVM.OrderHeader);
            OrderVM.RazorPayOptionModel = new RazorPayOptionModel()
            {
                Key = SD.PublishedKey,
                AmountInSubUnits = OrderVM.OrderHeader.OrderTotal,
                Currency = "INR",
                Name = OrderVM.OrderHeader.Name,
                Description = "Testing for RazorPya",
                ImageLogUrl = "",
                OrderId = razorOrderId,
                ProdileName = OrderVM.OrderHeader.Name,
                ProfileContact = OrderVM.OrderHeader.PhoneNumber,
                ProfileEmail = OrderVM.OrderHeader.ApplicationUser.Email,
                Notes = new Dictionary<string, string>()
                    {
                        {"note 1", "this is a payment note" },{"note 2", " here also you can add max 15 notes"}
                    },
                OrderHeaderId = OrderVM.OrderHeader.Id

            };

            TempData["OrderVM"] = JsonConvert.SerializeObject(OrderVM);
            // MakePayment();
            return RedirectToAction(nameof(Payment));

        }

        public IActionResult Payment(int Id)
        {
            TempData["orderHeaderId"] = null;

            if (TempData["OrderVM"] != null)
            {
                var orderVM = JsonConvert.DeserializeObject<OrderVM>(TempData["OrderVM"].ToString());
                TempData["orderHeaderId"] = orderVM.OrderHeader.Id;
                return View(orderVM);
            }


            return View();
        }

        public IActionResult AfterPayment()
        {
            try
            {
                // Helper method to safely extract values from Request.Form
                string GetFormValue(string key) => Request.Form.ContainsKey(key) ? Request.Form[key].ToString() : string.Empty;

                // Retrieve form values
                string orderId = GetFormValue("orderid");
                string paymentId = GetFormValue("paymentId");
                string signature = GetFormValue("signature");
                string paymentstatus = GetFormValue("paymentstatus");
                string id = GetFormValue("orderheaderid");



                // Validate mandatory fields
                if (string.IsNullOrEmpty(orderId) || string.IsNullOrEmpty(paymentId) ||
                    string.IsNullOrEmpty(signature) || string.IsNullOrEmpty(paymentstatus) || string.IsNullOrEmpty(id))
                {
                    TempData["error"] = "Payment Failed! Oops! Something went wrong while processing your payment.";
                    return View("PaymentFail");
                }

                // Check payment status and handle failure immediately
                if (paymentstatus == "Fail")
                {
                    TempData["error"] = "Payment Failed! Oops! Something went wrong while processing your payment.";
                    return RedirectToAction("PaymentFail");
                }

                int orderHeaderId = Convert.ToInt32(id);
                var orderHeader = _db.OrderHeader.Get(u => u.Id == orderHeaderId);

                // Validate the signature
                if (!CompareSignature(orderId, paymentId, signature))
                {
                    TempData["error"] = "Payment Failed! Oops! Something went wrong while processing your payment.";
                    return RedirectToAction("PaymentFail");
                }

                // Update payment info in the database

                _db.OrderHeader.UpdateStripePaymentId(orderHeaderId, signature, paymentId);

                // Only update the status if the payment was successful and not delayed
                if (paymentstatus == "Success" && orderHeader.PaymentStatus == SD.PaymentStatusDelayedPayment)
                {
                    _db.OrderHeader.UpdateStatus(orderHeaderId, orderHeader.OrderStatus, SD.PaymentStatusApproved);
                }

                _db.Commit();

                // Redirect to OrderConfirmation view
                return RedirectToAction(nameof(OrderConfirmation), new { id = orderHeaderId });
            }
            catch (Exception ex)
            {
                // Log exception (you may want to log this exception)
                TempData["error"] = "Payment Failed! Oops! Something went wrong while processing your payment.";
                return RedirectToAction("PaymentFail");
            }
        }

        public IActionResult OrderConfirmation(int id)
        {
            OrderHeader orderHeader = _db.OrderHeader.Get(u => u.Id == id, includeProperties: "ApplicationUser");

           

            return View(orderHeader.Id);
        }



        [HttpPost]
        [Authorize(Roles =SD.Role_Admin + "," + SD.Role_Employee )]
        public IActionResult UpdateOrderDetail(int orderId)
        {
            var orderHeaderFromDb = _db.OrderHeader.Get(u => u.Id == OrderVM.OrderHeader.Id);
            orderHeaderFromDb.Name = OrderVM.OrderHeader.Name;
            orderHeaderFromDb.PhoneNumber = OrderVM.OrderHeader.PhoneNumber;
            orderHeaderFromDb.StreetAddress = OrderVM.OrderHeader.StreetAddress;
            orderHeaderFromDb.City = OrderVM.OrderHeader.City;
            orderHeaderFromDb.State = OrderVM.OrderHeader.State;
            orderHeaderFromDb.PostalCode = OrderVM.OrderHeader.PostalCode;

            if (!string.IsNullOrEmpty(OrderVM.OrderHeader.Carrier))
            {
                orderHeaderFromDb.Carrier = OrderVM.OrderHeader.Carrier;
            }

            if (!string.IsNullOrEmpty(OrderVM.OrderHeader.TrackingNumber))
            {
                orderHeaderFromDb.TrackingNumber = OrderVM.OrderHeader.TrackingNumber;
            }
            _db.OrderHeader.Update(orderHeaderFromDb);
            _db.Commit();
            TempData["success"] = "Order Detail Updated Successfully.";

            return RedirectToAction(nameof(Details), new {orderId = orderHeaderFromDb.Id});
        }

        [HttpPost]
        [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Employee)]
        public IActionResult StartProcessing()
        {
            _db.OrderHeader.UpdateStatus(OrderVM.OrderHeader.Id, SD.StatusInProgress);
            _db.Commit();
            TempData["success"] = "Order Status Updated to Inprogress!!";
            return RedirectToAction(nameof(Details), new {orderId = OrderVM.OrderHeader.Id});

        }

        [HttpPost]
        [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Employee)]
        public IActionResult ShipOrder()
        {
            var orderHeaderFromDb = _db.OrderHeader.Get(u => u.Id == OrderVM.OrderHeader.Id);
            orderHeaderFromDb.TrackingNumber = OrderVM.OrderHeader.TrackingNumber;
            orderHeaderFromDb.Carrier = OrderVM.OrderHeader.Carrier;
            orderHeaderFromDb.OrderStatus = SD.StatusShipped;
            orderHeaderFromDb.ShippingDate = DateTime.Now;

            if(orderHeaderFromDb.PaymentStatus == SD.PaymentStatusDelayedPayment)
            {
                orderHeaderFromDb.PaymentDueDate = DateOnly.FromDateTime(DateTime.Now.AddDays(30));
            }

            _db.OrderHeader.Update(orderHeaderFromDb);
            _db.Commit();

            TempData["success"] = "Order Shipped Successfully!!";
            return RedirectToAction(nameof(Details), new { orderId = OrderVM.OrderHeader.Id });

        }

        [HttpPost]
        [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Employee)]
        public IActionResult CancelOrder()
        {
            var orderHeaderFromDb = _db.OrderHeader.Get(u => u.Id == OrderVM.OrderHeader.Id);
           
            if(orderHeaderFromDb.PaymentStatus == SD.PaymentStatusApproved)
            {
                //Razor pay refund code will come , Please check out on razor pay doc.

                try
                {
                    // Call Razorpay refund API
                    var refund = _razorpayService.RefundPayment(orderHeaderFromDb.PaymentIntentId, orderHeaderFromDb.OrderTotal);

                    if (refund != null)
                    {
                        //return Ok(new
                        //{
                        //    success = true,
                        //    refund = refund
                        //});

WalmartWeb/ViewComponents/ShoppingCartViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Walmart.DataAccess.Repository.IRepository;
using Walmart.Utility;

namespace WalmartWeb.ViewComponents
{
    // Its like master page having .cs file to code C# code and have some logic.
    public class ShoppingCartViewComponent : ViewComponent
    {
        private readonly IUnitOfWork _unitOfWork;

        public ShoppingCartViewComponent(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var claimsIdentity = (ClaimsIdentity?)User.Identity;
            var claim = (claimsIdentity?.FindFirst(ClaimTypes.NameIdentifier));
            if (claim != null)
            {
                if(HttpContext.Session.GetInt32(SD.SessionCart) == null)
                {
                    HttpContext.Session.SetInt32(SD.SessionCart, _unitOfWork.ShoppingCart.GetAll(u => u.ApplicationUserId == claim.Value).Count());
                }
                return View(HttpContext.Session.GetInt32(SD.SessionCart));

            }
            else
            {
                HttpContext.Session.Clear();
                return View(0);

            }

        }

    }
}

WalmartWeb/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] N - MART</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WalmartWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/2.2.1/css/dataTables.dataTables.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.3/css/jquery.dataTables.min.css"/>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-info  border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand bg-gradient link-opacity-10-hover" asp-area="Customer" asp-controller="Home" asp-action="Index"><img width="50" height="35" src="https://img.icons8.com/3d-fluency/94/shopping-bag.png" alt="NMART Online Shopping" />N-MART</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark link-opacity-10-hover" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                       
                       
                            <li class="nav-item">
                                <a class="nav-link text-dark link-opacity-10-hover" asp-area="Customer" asp-controller="Cart" asp-action="Index">
                                 Cart  @await Component.InvokeAsync("ShoppingCart")
                                </a>
                            </li>
                       
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark link-opacity-10-hover" asp-area="Admin" asp-controller="Order" asp-action="Index"> Manage Order
                                <img width="30" height="30" src="https://img.icons8.com/parakeet-line/48/purchase-order.png" alt="purchase-order" />
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark link-opacity-10-hover" asp-area="Customer" asp-controller="Contact" asp-action="Index">Contact</a>
                        </li>

                        @if(User.IsInRole(SD.Role_Admin)){

                        <li class="nav-item">
                            <a class="nav-link text-dark link-opacity-10-hover" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>

                        </li>
                        
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Users" asp-action="Index">Users</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Company" asp-action="Index">Company</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Register">Create User</a>
                            </li>
                        }
                       
                       
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            Made with <i class="bi bi-heart-fill"></i> by <b><i>JARNY Software Solutions.</i></b>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.js"></script>
    <script src="https://cdn.tiny.cloud/1/frb3g2i4edyi1nc41xwd3qe9h51vfkhy1kxm6w5eu26nb6lt/tinymce/7/tinymce.min.js" referrerpolicy="origin"></script>
    <script src="https://cdn.datatables.net/1.13.3/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WalmartWeb/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
		<script src="~/lib/jquery/dist/jquery.min.js"></script>
		<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
		<script type="text/javascript">

			toastr.success('@TempData["success"]');
		</script>
}

@if (TempData["error"] != null) @*We have added any error key with TempData but in future we can use like this in our code.*@
{
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
		<script type="text/javascript">

			toastr.error('@TempData["error"]');
		</script>
}